# Generated by Django 2.2 on 2019-04-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_description', models.CharField(max_length=30)),
                ('product_amount', models.IntegerField()),
                ('product_value', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
